<<<<<<< Updated upstream
import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from '@/components/layout';

const inter = Inter({ subsets: ["latin"] });
=======
import Head from 'next/head'
>>>>>>> Stashed changes

export default function Home() {

  return (
    <>
      <Head>
<<<<<<< Updated upstream
        <title>ToDo List</title>
        <meta
          name='description'
          content='App que permite administrar una lista de tareas'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
      
      </Layout>
=======
        <title>Lista de Tareas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
>>>>>>> Stashed changes
    </>
  );
}
