# Generated by Django 4.2.7 on 2023-11-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriaCuenta',
        ),
        migrations.RemoveField(
            model_name='cajaahorro',
            name='account',
        ),
        migrations.RemoveField(
            model_name='clienteblack',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='clienteclassic',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='clientegold',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='account',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Errores',
        ),
        migrations.DeleteModel(
            name='MarcaTarjeta',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='tarjeta_numero',
        ),
        migrations.RemoveField(
            model_name='tarjetadebito',
            name='tarjeta_numero',
        ),
        migrations.DeleteModel(
            name='TipoMoneda',
        ),
        migrations.DeleteModel(
            name='CajaAhorro',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClienteBlack',
        ),
        migrations.DeleteModel(
            name='ClienteClassic',
        ),
        migrations.DeleteModel(
            name='ClienteGold',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='CuentaCorriente',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
        migrations.DeleteModel(
            name='TarjetaDebito',
        ),
    ]
