# Generated by Django 4.2.7 on 2023-11-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriacuenta',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
