# Generated by Django 4.2.7 on 2023-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
