# Generated by Django 4.2.7 on 2023-12-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagoservicio',
            table='pagos_servicio',
        ),
    ]
