# Generated by Django 4.2.7 on 2023-11-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_userprofile_dni_alter_userprofile_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
    ]
