# Generated by Django 4.2.7 on 2023-12-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('marca_tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_tarjeta_nombre', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tarjeta_numero', models.AutoField(primary_key=True, serialize=False)),
                ('tarjeta_cvv', models.IntegerField(db_column='tarjeta_CVV')),
                ('tarjeta_fecha_otorgamiento', models.TextField()),
                ('tarjeta_fecha_expiracion', models.TextField()),
                ('tarjeta_nombre_propietario', models.TextField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('tarjeta_numero', models.OneToOneField(db_column='tarjeta_numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
                ('cantidad_extensiones', models.IntegerField()),
                ('limite_en_un_pago', models.FloatField()),
                ('limite_en_cuotas', models.FloatField()),
            ],
            options={
                'db_table': 'tarjeta_credito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaDebito',
            fields=[
                ('tarjeta_numero', models.OneToOneField(db_column='tarjeta_numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
            ],
            options={
                'db_table': 'tarjeta_debito',
                'managed': False,
            },
        ),
    ]
